import Head from 'next/head'
import blogContext, { fetchPosts } from '@/store/context';
import Blog from './blogs';
import Menu from './../Components/navbar/Menu';
export default function Home({reviews}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Menu/>
    <Blog
    reviews={reviews}
    />
    </>
  )
}
export async function getServerSideProps(){
  const data = await fetchPosts();
  console.log('data:', data);
  return {
    props: {
      reviews: data.slice(0, 6),
    },
  };
}