import Head from 'next/head'

// import Blog from './Blogs/Blogs';

import Detail from './Details/[id]';

import { useEffect , useState, useContext } from 'react';
import blogContext, { fetchPosts } from '@/store/context';

import Blog from './Blogs';


export default function Home({reviews}) {
  // const [posts, setPosts] = useState([]);

  // console.log(reviews);
  // useEffect(() => {
  //   const fetchData = async () => {
  //     const data  = await fetchPosts();
  //     // console.log(data);
  //   }
  //   fetchData();
  // }, [fetchPosts]);

  // console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    <Blog
    reviews={reviews}
    />
    </>
  )
}


export async function getServerSideProps(){
  const data = await fetchPosts();

  console.log('data:', data);

  return {
    props: {
      reviews: data.slice(0, 6),
    },
  };
}